// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: protos/general.proto

/* eslint-disable */

export const protobufPackage = "general";

export interface Empty {
}

export const GENERAL_PACKAGE_NAME = "general";
