// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: general.proto

/* eslint-disable */

export const protobufPackage = "v1.general";

export interface Empty {
}

export interface PageInfo {
  page: number;
  pageSize: number;
  totalPages: number;
  totalItems: number;
  nextCursor: string;
  hasMore: boolean;
}

export const V1_GENERAL_PACKAGE_NAME = "v1.general";
