// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: protos/v1/messages.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./general";
import { User } from "./users";

export const protobufPackage = "v1.messages";

export interface UpdateMessageDto {
  id: number;
  content?: string | undefined;
}

export interface RemoveMessageDto {
  id?: number | undefined;
  senderId?: number | undefined;
  receiverId?: number | undefined;
  content?: string | undefined;
  createdAt?: string | undefined;
}

export interface SendMessageDto {
  senderId: number;
  receiverId: number;
  content: string;
}

export interface GetMessageDto {
  id?: number | undefined;
  senderId?: number | undefined;
  receiverId?: number | undefined;
  content?: string | undefined;
  createdAt?: string | undefined;
  viewerId?: string | undefined;
  viewedAt?: string | undefined;
}

export interface MessageResponse {
  status: string;
  result: Message | undefined;
  message?: string | undefined;
}

export interface MessagesResponse {
  status: string;
  result: Messages | undefined;
  message?: string | undefined;
}

export interface Messages {
  messages: Message[];
}

export interface Message {
  id: number;
  senderId: number;
  receiverId: number;
  content: string;
  createdAt: string;
  viewers: Viewers | undefined;
}

export interface Viewers {
  viewers: Viewer[];
}

export interface Viewer {
  user: User | undefined;
  viewedAt: string;
}

export const V1_MESSAGES_PACKAGE_NAME = "v1.messages";

export interface MessagesServiceClient {
  getMessage(request: Empty): Observable<MessagesResponse>;

  getOneMessage(request: GetMessageDto): Observable<MessageResponse>;

  getSomeMessages(request: GetMessageDto): Observable<MessageResponse>;

  sendMessage(request: SendMessageDto): Observable<MessageResponse>;

  removeMessage(request: RemoveMessageDto): Observable<MessageResponse>;

  updateMessage(request: UpdateMessageDto): Observable<MessageResponse>;
}

export interface MessagesServiceController {
  getMessage(request: Empty): Observable<MessagesResponse>;

  getOneMessage(request: GetMessageDto): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  getSomeMessages(request: GetMessageDto): Observable<MessageResponse>;

  sendMessage(request: SendMessageDto): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  removeMessage(request: RemoveMessageDto): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;

  updateMessage(request: UpdateMessageDto): Promise<MessageResponse> | Observable<MessageResponse> | MessageResponse;
}

export function MessagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getMessage",
      "getOneMessage",
      "getSomeMessages",
      "sendMessage",
      "removeMessage",
      "updateMessage",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MessagesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MESSAGES_SERVICE_NAME = "MessagesService";
