// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.5
// source: users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./general";

export const protobufPackage = "v1.users";

export interface DeleteResponse {
  status: string;
  result: boolean;
  message?: string | undefined;
}

export interface DeleteUserByIdDto {
  id: number;
}

export interface GetUserByIdDto {
  id: number;
}

export interface GetSomeUsersByIdsDto {
  ids: number[];
}

export interface GetSomeUsersByUsernameDto {
  username: string;
}

export interface UsersResponse {
  status: string;
  result: Users | undefined;
  message?: string | undefined;
}

export interface Users {
  users: User[];
}

export interface UserResponse {
  status: string;
  result: User | undefined;
  message?: string | undefined;
}

export interface User {
  id: number;
}

export const V1_USERS_PACKAGE_NAME = "v1.users";

export interface UsersServiceClient {
  getUsers(request: Empty): Observable<UsersResponse>;

  getUserById(request: GetUserByIdDto): Observable<UserResponse>;

  getSomeUsersByIds(request: GetSomeUsersByIdsDto): Observable<UsersResponse>;

  getSomeUsersByUsername(request: GetSomeUsersByUsernameDto): Observable<UsersResponse>;

  createUser(request: User): Observable<UserResponse>;

  updateUser(request: User): Observable<UserResponse>;

  deleteUserById(request: DeleteUserByIdDto): Observable<DeleteResponse>;
}

export interface UsersServiceController {
  getUsers(request: Empty): Observable<UsersResponse>;

  getUserById(request: GetUserByIdDto): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getSomeUsersByIds(request: GetSomeUsersByIdsDto): Observable<UsersResponse>;

  getSomeUsersByUsername(request: GetSomeUsersByUsernameDto): Observable<UsersResponse>;

  createUser(request: User): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(request: User): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  deleteUserById(request: DeleteUserByIdDto): Promise<DeleteResponse> | Observable<DeleteResponse> | DeleteResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUsers",
      "getUserById",
      "getSomeUsersByIds",
      "getSomeUsersByUsername",
      "createUser",
      "updateUser",
      "deleteUserById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
