connector.name=cassandra
cassandra.contact-points=cassandra
cassandra.native-protocol-port=9042
# If Cassandra auth is enabled, uncomment these:
# cassandra.username=YOUR_USERNAME
# cassandra.password=YOUR_PASSWORD
