services:
  main-sql:
    container_name: nest-main-sql
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network
  main-nosql:
    image: cassandra:4.1
    container_name: nest-main-nosql-instance-1
    hostname: nest-main-nosql-instance-1
    environment:
      - CASSANDRA_CLUSTER_NAME=PayamvarCluster
      - CASSANDRA_NUM_TOKENS=16
      - CASSANDRA_START_RPC=true
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    depends_on:
      - main-sql
    restart: unless-stopped
    networks:
      - backend-network
  main-nosql-2:
    image: cassandra:4.1
    container_name: nest-main-nosql-instance-2
    hostname: nest-main-nosql-instance-2
    volumes:
      - cassandra_data_2:/var/lib/cassandra
      - ./init-cassandra-config.sh:/init-cassandra-config.sh
    entrypoint: ["/bin/bash", "/init-cassandra-config.sh"]
    env_file:
      - .env
    depends_on:
      - main-sql
      - main-nosql
    restart: unless-stopped
    networks:
      - backend-network
  
  main-nosql-3:
    image: cassandra:4.1
    container_name: nest-main-nosql-instance-3
    hostname: nest-main-nosql-instance-3
    volumes:
      - cassandra_data_3:/var/lib/cassandra
      - ./init-cassandra-config.sh:/init-cassandra-config.sh
    entrypoint: ["/bin/bash", "/init-cassandra-config.sh"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - main-sql
      - main-nosql
    networks:
      - backend-network

  datastax-studio:
    image: datastax/dse-studio
    container_name: nosql-studio
    ports:
      - "9091:9091"
    environment:
      - DS_LICENSE=accept
    networks:
      - backend-network

  grafana-management-panel:
    image: grafana/grafana:latest
    container_name: grafana-management-panel
    ports:
      - "4545:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  cassandra_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/cassandra-data
      o: bind
  cassandra_data_2:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/cassandra-data-2
      o: bind
  cassandra_data_3:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/cassandra-data-3
      o: bind
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/pgdata
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/grafana-data
      o: bind
  # prometheus-data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ${PWD}/docker/prometheus-data
  #     o: bind