-- Your SQL goes here
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    password TEXT,
    created_at TIMESTAMP DEFAULT(CURRENT_TIMESTAMP),
    updated_at TIMESTAMP DEFAULT(CURRENT_TIMESTAMP),
    deleted_at TIMESTAMP NULL 
);